export const APP_READY = 'APP_READY';
export const ADD_NOTES = 'ADD_NOTES';
export const TOGGLE_ACTIVE_MODE = 'TOGGLE_ACTIVE_MODE';
export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const TOGGLE_CONFIRMATION_DIALOG = 'TOGGLE_CONFIRMATION_DIALOG';
